# Site settings
title: "Julia Hilton - Colorado Piano Teacher"
description: "Julia Hilton has been teaching 30+ beginner to advanced classical and jazz piano students for over a decade.  Her studio serves Broomfield, Westminster, Northglenn, Thornton, Arvada, and North Denver."
email: julia@coloradopianoteacher.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coloradopianoteacher.com" # the base hostname & protocol for your site
twitter_username: copianoteacher
permalink: /:year-:month_:title.html

# Build settings
markdown: kramdown

exclude: ['Gemfile*','cloudfiles_upload.rb']

sass:
    sass_dir: _sass

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "events"
      type: "posts"
    values:
      layout: "event"
      categories: "event"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # overrides previous default layout
