backend:
  name: github
  repo: coloradopianoteacher/coloradopianoteacher.github.io # Path to your GitHub repository
  # optional, defaults to master
  # branch: main

  
media_folder: 'assets'
public_folder: ""

collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "Schedule Page"
      name: "about"
      file: "schedule.html"
      fields:
        - {label: Title, name: title, widget: string}
        - label: 'Code'
          name: 'code'
          widget: 'code'
          default_language: 'html'
